
CREATE TABLE Audit_Log (
    Log_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    User_Name     VARCHAR2(30),
    Operation     VARCHAR2(10),
    Table_Name    VARCHAR2(30),
    Status        VARCHAR2(10),
    Attempt_Time  TIMESTAMP DEFAULT SYSTIMESTAMP,
    Error_Message VARCHAR2(200)
);
