--Triggers
CREATE OR REPLACE TRIGGER trg_medicines_bi BEFORE INSERT ON Medicines FOR EACH ROW
BEGIN IF :NEW.Medicine_ID IS NULL THEN SELECT seq_medicines.NEXTVAL INTO :NEW.Medicine_ID FROM DUAL; END IF; END;
/

CREATE OR REPLACE TRIGGER trg_suppliers_bi BEFORE INSERT ON Suppliers FOR EACH ROW
BEGIN IF :NEW.Supplier_ID IS NULL THEN SELECT seq_suppliers.NEXTVAL INTO :NEW.Supplier_ID FROM DUAL; END IF; END;
/

CREATE OR REPLACE TRIGGER trg_branches_bi BEFORE INSERT ON Branches FOR EACH ROW
BEGIN IF :NEW.Branch_ID IS NULL THEN SELECT seq_branches.NEXTVAL INTO :NEW.Branch_ID FROM DUAL; END IF; END;
/

CREATE OR REPLACE TRIGGER trg_batches_bi BEFORE INSERT ON Batches FOR EACH ROW
BEGIN IF :NEW.Batch_ID IS NULL THEN SELECT seq_batches.NEXTVAL INTO :NEW.Batch_ID FROM DUAL; END IF; END;
/

CREATE OR REPLACE TRIGGER trg_inventory_bi BEFORE INSERT ON Inventory FOR EACH ROW
BEGIN IF :NEW.Inventory_ID IS NULL THEN SELECT seq_inventory.NEXTVAL INTO :NEW.Inventory_ID FROM DUAL; END IF; END;
/

CREATE OR REPLACE TRIGGER trg_users_bi BEFORE INSERT ON Users FOR EACH ROW
BEGIN IF :NEW.User_ID IS NULL THEN SELECT seq_users.NEXTVAL INTO :NEW.User_ID FROM DUAL; END IF; END;
/

CREATE OR REPLACE TRIGGER trg_transactions_bi BEFORE INSERT ON Transactions FOR EACH ROW
BEGIN IF :NEW.Transaction_ID IS NULL THEN SELECT seq_transactions.NEXTVAL INTO :NEW.Transaction_ID FROM DUAL; END IF; END;
/

CREATE OR REPLACE TRIGGER trg_ti_bi BEFORE INSERT ON Transaction_Items FOR EACH ROW
BEGIN IF :NEW.Transaction_Item_ID IS NULL THEN SELECT seq_transaction_items.NEXTVAL INTO :NEW.Transaction_Item_ID FROM DUAL; END IF; END;
/

CREATE OR REPLACE TRIGGER trg_predictions_bi BEFORE INSERT ON Predictions FOR EACH ROW
BEGIN IF :NEW.Prediction_ID IS NULL THEN SELECT seq_predictions.NEXTVAL INTO :NEW.Prediction_ID FROM DUAL; END IF; END;
/

CREATE OR REPLACE TRIGGER trg_alerts_bi BEFORE INSERT ON Alerts FOR EACH ROW
BEGIN IF :NEW.Alert_ID IS NULL THEN SELECT seq_alerts.NEXTVAL INTO :NEW.Alert_ID FROM DUAL; END IF; END;
/

CREATE OR REPLACE TRIGGER trg_transfers_bi BEFORE INSERT ON Transfers FOR EACH ROW
BEGIN IF :NEW.Transfer_ID IS NULL THEN SELECT seq_transfers.NEXTVAL INTO :NEW.Transfer_ID FROM DUAL; END IF; END;
/
COMMIT;
