-- create admin user
CREATE USER INEZA_ESPERANCE
IDENTIFIED BY ESPERANCE
DEFAULT TABLESPACE smart_data_tbs
TEMPORARY TABLESPACE smart_temp_tbs
QUOTA UNLIMITED ON smart_data_tbs
QUOTA UNLIMITED ON smart_index_tbs;
--grant required roles and privilages
GRANT CONNECT, RESOURCE TO INEZA_ESPERANCE;
GRANT DBA TO INEZA_ESPERANCE;
