CREATE TABLESPACE smart_index_tbs
DATAFILE 'C:\ORACLE21C\ORADATA\ORCL\wed_28777_esperance_Smart_Medecine_Inventory_DB\smart_index_tbs01.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 10M MAXSIZE 500M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;
