CREATE PLUGGABLE DATABASE wed_28777_esperance_Smart_Medecine_Inventory_DB
ADMIN USER pdbadmin IDENTIFIED BY Ineza
ROLES = (DBA)
FILE_NAME_CONVERT = ('C:\ORACLE21C\ORADATA\ORCL\PDBSEED\', 'C:\ORACLE21C\ORADATA\ORCL\wed_28777_esperance_Smart_Medecine_Inventory_DB\');
