ALTER PLUGGABLE DATABASE OPEN;
CREATE TABLESPACE smart_data_tbs
DATAFILE 'C:\ORACLE21C\ORADATA\ORCL\wed_28777_esperance_Smart_Medecine_Inventory_DB\smart_data_tbs01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE 1G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;
